### ISSUE TITLE
Discount is not working for whole sale price in cart page 

### ISSUE THREAD

**Issue by Divya-savi** [flycartinc/woo-wholesale-price-compatibility#2]
step to reproduce :
Rule page 
![image](https://github.com/flycartinc/woo-wholesale-price-compatibility/assets/149564255/b40b5c08-3bb4-4308-8aa4-fc38d82f64b0)
shop page :
![image](https://github.com/flycartinc/woo-wholesale-price-compatibility/assets/149564255/d14a9d33-9dcb-46c7-b4a3-b2a1475b62f1)
cart page 
![image](https://github.com/flycartinc/woo-wholesale-price-compatibility/assets/149564255/cb50e28b-a9d2-40e4-81e9-e31a434d63f4)

**Comment by HemaR03** [comment]
Issue Fixed
![image](https://github.com/user-attachments/assets/b3da3682-8e02-4c52-8e27-6c527fdbbb9a)
![image](https://github.com/user-attachments/assets/aee94a09-bb18-44d5-a36c-b669efbb4702)
![image](https://github.com/user-attachments/assets/f8a00f11-094a-443a-a37c-2d4656ba5ba2)
