### ISSUE TITLE
wholesale -  Discount applied as coupon format , while after remove the product in cart , it shows empty page 

### ISSUE THREAD

**Issue by Divya-savi** [flycartinc/woo-wholesale-price-compatibility#20]
![image](https://github.com/flycartinc/woo-wholesale-price-compatibility/assets/149564255/50983441-5b86-45ea-b012-17872cd1a6e9)
[Screencast from 2024-06-20 11-50-43.webm](https://github.com/flycartinc/woo-wholesale-price-compatibility/assets/149564255/46493f21-853a-4683-b961-4925d7525b3a)

**Comment by HemaR03** [comment]
Issue Fixed
![image](https://github.com/user-attachments/assets/5d1a2371-64e9-45fb-af7d-764b0f7d0f9e)
![image](https://github.com/user-attachments/assets/f437759f-7385-4c8e-bb00-3b98fd502f2e)
[Screencast from 09-08-24 11:15:17 AM IST.webm](https://github.com/user-attachments/assets/9b2d286e-5629-4476-b8b9-cda2a7df4912)
