### ISSUE TITLE
Discount is not applied , while using the coupon as a discount 

### ISSUE THREAD

**Issue by Divya-savi** [flycartinc/woo-wholesale-price-compatibility#21]
Discount applied first time as a normal discount , while after change the discount as coupon , at that time discount is not applied while after refresh the page 
![image](https://github.com/flycartinc/woo-wholesale-price-compatibility/assets/149564255/235f92a5-28a4-4b28-89f6-64a50263083c)
[Screencast from 2024-07-11 15-05-25.webm](https://github.com/flycartinc/woo-wholesale-price-compatibility/assets/149564255/fbbf15fc-e226-401f-984d-a78bd8b16471)

**Comment by HemaR03** [comment]
Issue Fixed
![image](https://github.com/user-attachments/assets/3cae828a-7863-4bda-b444-ad277880ba3b)
![image](https://github.com/user-attachments/assets/6622f762-402c-4fb3-84b0-d077a0d3d5c8)
![image](https://github.com/user-attachments/assets/6fb9bcc7-f2de-48ed-80d8-896de726d5fa)
[Screencast from 09-08-24 11:43:39 AM IST.webm](https://github.com/user-attachments/assets/3a5c1554-cc96-4f7c-814a-9e050089e971)
