### ISSUE TITLE
discount not applied coorectly while using subtotal conditions 

### ISSUE THREAD

**Issue by Divya-savi** [flycartinc/woo-wholesale-price-compatibility#23]
![image](https://github.com/user-attachments/assets/e97d1f31-3b8c-4e34-8593-6ee476056a3e)
![image](https://github.com/user-attachments/assets/bc7d1b9a-ba69-48fa-9837-73a14f4763ad)

**Comment by HemaR03** [comment]
Issue Fixed
![image](https://github.com/user-attachments/assets/b4d7f077-c721-4b67-a869-2bbe20f049ab)
![image](https://github.com/user-attachments/assets/ba217681-d96b-400b-a958-c7bd878d7a25)
![image](https://github.com/user-attachments/assets/f28e79ab-2930-4d41-9604-aa7b398d9138)
