### ISSUE TITLE
whole sale price is not shown , while discount rule is applied 

### ISSUE THREAD

**Issue by Divya-savi** [flycartinc/woo-wholesale-price-compatibility#24]
![image](https://github.com/user-attachments/assets/15caa950-9e76-4734-a92f-2b9bc15dc0cc)
cart page 
![image](https://github.com/user-attachments/assets/c5e3f774-d65d-4c8b-823d-6f76a20ab784)
product page 
![image](https://github.com/user-attachments/assets/c52d06f6-a53c-4d9c-a190-5ca56f90842c)

**Comment by HemaR03** [comment]
Issue Fixed
![image](https://github.com/user-attachments/assets/4783b1cd-accd-4e82-877a-786bca486738)
![image](https://github.com/user-attachments/assets/95fa0388-415c-4a67-a3c8-b3fdcb71e2eb)
![image](https://github.com/user-attachments/assets/fd98316c-5edf-4c81-806c-96577715ed10)
